### ISSUE TITLE
Windows/Linux Reqwest Error 

### ISSUE THREAD

**Issue by JuniperMS** [mateoradman/bazarr-bulk#1]
When attempting to use the script on Windows 10, I get this error message in command prompt and PowerShell stating, "Error: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 5030) }". I have the "bb" and "config.json" file in the Downloads directory. Below is an output from PowerShell.

PS C:\Users\User1\Downloads> ls
Directory: C:\Users\User1\Downloads

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/22/2024   7:08 AM                bazarr-bulk_v.0.1.1_x86_64-pc-windows-gnu
-a----         1/22/2024   7:08 AM        5306389 bazarr-bulk_v.0.1.1_x86_64-pc-windows-gnu.zip
-a----          1/7/2024   2:02 PM       16944547 bb.exe
-a----         1/22/2024   7:25 AM            118 config.json

PS C:\Users\User1\Downloads> .\bb.exe --config .\config.json tv-shows sync
Error: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 5030) }

**Configuration File:**

{
"host": "192.168.30.37",
"protocol": "http",
"port": "6767",
"apiKey": "REMOVED"
}

**Comment by mateoradman** [comment]
Thank you for reporting this issue @JuniperMS. It seems that a struct is expecting a string but is getting a null value from bazarr's API. I will figure out which fields are nullable and which aren't from bazarr's source code and that will resolve the problem.

**Comment by mateoradman** [comment]
Hi @JuniperMS, what is the version of Bazarr you're running?

**Comment by JuniperMS** [comment]
Hi @mateoradman, I'm running Bazarr 1.4.0.
