### ISSUE TITLE
Segmentation fault when running 0.1.3

### ISSUE THREAD

**Issue by douglasparker** [mateoradman/bazarr-bulk#10]
There is a segmentation fault when running v0.1.3 using the Linux binaries. This happens not only with sync, but the other commands as well.

**Comment by mateoradman** [comment]
Hey, I've updated the [v0.1.3](https://github.com/mateoradman/bazarr-bulk/releases/tag/v0.1.3) linux binary . It should work now.

**Comment by douglasparker** [comment]
Working good now, thank you so much!
