### ISSUE TITLE
Enhancement proposal: display progress in a better way

### ISSUE THREAD

**Issue by douglasparker** [mateoradman/bazarr-bulk#11]
Sync sits and 0/xxx and doesn’t seem to progress.

**Comment by mateoradman** [comment]
I wanted to get the `Mod Sync not loaded` bug out of the way. I plan to improve on how the progress is displayed in the next release. Generally, syncing is a CPU-intensive task and takes time to complete. Depending on the size of your library, it can take hours/days.

**Comment by douglasparker** [comment]
> I wanted to get the `Mod Sync not loaded` bug out of the way. I plan to improve on how the progress is displayed in the next release. Generally, syncing is a CPU-intensive task and takes time to complete. Depending on the size of your library, it can take hours/days.

Sounds good, thank you so much!!
