### ISSUE TITLE
Movies offset

### ISSUE THREAD

**Issue by JuacOHI** [mateoradman/bazarr-bulk#24]
Hello. How are you doing ? First of all, thanks for creating this tool of mass sync.

Im having an issue with this tool, i had to restart my computer and i used the -offset to skip the ones that i already synced, but it seems that it didn't work. Is this option working?. Here is a screenshot: https://imgur.com/a/PGWc4fc
![bazarr-bulk](https://github.com/mateoradman/bazarr-bulk/assets/47452972/a4ecfbc5-1e1d-4708-8f71-9d6f571d3f5b)

You can tell that my library its on the big side, almost 6000 and each one has 4 different languages, so if i resync everything its gonna take me a lot of days.

Thanks again for the tool.

**Comment by mateoradman** [comment]
Hi @JuacOHI, thanks for reporting the problem. I will test the feature again, and report back as soon as possible.

**Comment by mateoradman** [comment]
I've investigated this problem, and it seems that Bazarr's API only respects the `start` query parameter (I call it `offset`) in combination with the `length` query parameter (I call it `limit`). When `start` is set, but `length` is not, Bazarr sets `length` to -1 which retreives all results regardless of the `start` query param. I managed to come up with a workaround for this problem which does the following:

- if offset is set, but limit is not set, set limit to max unsigned 32-bit integer (4294967295).

**Comment by JuacOHI** [comment]
Thank you for the quick reply and solution.
I tried with the max integer and didn't work, but it did work when i put the limit number with the total of my library

![bazarr-bulk](https://github.com/mateoradman/bazarr-bulk/assets/47452972/dff4f1f2-de54-4d6e-8c71-8b599b64d8ca)
![bazarr-bulk2](https://github.com/mateoradman/bazarr-bulk/assets/47452972/4aba9975-9a09-484c-a9c4-3d199629d033)

**Comment by mateoradman** [comment]
> Thank you for the quick reply and solution.
> 
> I tried with the max integer and didn't work, but it did work when i put the limit number with the total of my library
> 
> 
> 
> ![bazarr-bulk](https://github.com/mateoradman/bazarr-bulk/assets/47452972/dff4f1f2-de54-4d6e-8c71-8b599b64d8ca)
> 
> ![bazarr-bulk2](https://github.com/mateoradman/bazarr-bulk/assets/47452972/4aba9975-9a09-484c-a9c4-3d199629d033)
> 
> 

Thank you for the confirmation. An official fix for this problem is going to be included in the next release.
