### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by huuub** [mateoradman/bazarr-bulk#38]
Nomatter what I try in the config I keep getting:
Error while connecting to Bazarr.

I use a docker container with 6767:6767
I tried my ip of the server where it is running, localhost, 0.0.0.0, 127.0.0.1.
It never can connect?

**Comment by mateoradman** [comment]
Hi @huuub,

Can you please try to connect to your bazarr instance using cURL or a similar http client?
For example:

```bash
curl -X 'GET' \
  'http://192.168.1.114:6767/api/system/health' \
  -H 'accept: application/json'
```

should return the response:

`"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}`

If you don't get this response, then the machine you are trying to run bazarr-bulk on cannot communicate with the machine that is running Bazarr on the IP:PORT that you expect it to.

**Comment by huuub** [comment]
Exactly what I get:
➜  bazarr-bulk curl -X 'GET' \
  'http://192.168.1.5:6767/api/system/health' \ 
  -H 'accept: application/json'
{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}

**Comment by hyperactive68** [comment]
> I found my mistake. I needed to empty the optional parameter BASEURL.

I was getting an "unauthorized request" error and doing this fixed it for me as well. Thanks!

**Comment by huuub** [comment]
As it was optional I thought it would not break anything maybe adjust the documentation to avoid this confusion?

**Comment by mateoradman** [comment]
Thanks for your feedback. I've updated the README file with Configuration option section which holds explanations of what each configuration option represents. I've also updated the example config.json file to have an empty string as a default baseUrl.
