### ISSUE TITLE
Error: reqwest::Error 

### ISSUE THREAD

**Issue by madejackson** [mateoradman/bazarr-bulk#7]
I get following Error trying to run any command:

```
Bazarr API is healthy.
Error: reqwest::Error { kind: Decode, source: Error("expected value", line: 4, column: 1) }
```
Bazarr is V1.4.2 on k3s behind traefik with authentik (/api is excluded from authentik)

`{
  "host": "bazarr.local.REDACTED",
  "protocol": "https",
  "port": "443",
  "apiKey": "REDACTED"
}`

Tried from Pop!OS 22.04 with bazarr-bulk 0.1.2 (installed automatically or manually, same issue)

**Comment by mateoradman** [comment]
Hi @madejackson, thanks for reporting this bug. I will need a few more information to be able to work on this.
1. Which operation did you try to run? (Syncing, OCR Fixes, ...)
2. Were you attempting to perform actions on movie or tv show subtitles?
3. Are there any bazarr logs suggesting that something went wrong while using Bazarr bulk CLI? (System > Logs)

**Comment by madejackson** [comment]
Yes no Problem,

Here you go, once with and without value provided:

Episodes for series with ID 1:
[response_1710154203699.json](https://github.com/mateoradman/bazarr-bulk/files/14557344/response_1710154203699.json)

Movies (length 100):
[response_1710154365768.json](https://github.com/mateoradman/bazarr-bulk/files/14557398/response_1710154365768.json)

Headers:
>  access-control-allow-origin: *  content-encoding: gzip  content-length: 38458  content-type: application/json  date: Mon,11 Mar 2024 10:52:44 GMT  server: waitress  vary: Accept-Encoding  x-firefox-spdy: h2

**Comment by Fratt** [comment]
I'm experiencing the same issue as him

```
bb --config config.json movies sync
Bazarr API is healthy.
Error: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
```

my config.json looks like
```
{
  "host": "192.168.1.2",
  "protocol": "http",
  "port": "6767",
  "apiKey": "xxx"
}
```

Something that might be relevant is that the base URL of Bazarr is not `/`, but `bazarr/`.
Meaning that my Bazarr is reached under `http://192.168.1.2:6767/bazarr/`
And the API under `http://192.168.1.2/bazarr/api/`

**Comment by mateoradman** [comment]
Thank you for reaching out! I am working on reproducing this bug.

Additionally, I will improve the error reporting procedure in v1.4 which will help detecting what went wrong.

**Comment by matt1432** [comment]
I have the exact same issue with a base URL

**Comment by andonevris** [comment]
Exactly the same error here, also using a base URL

Bazarr Bulk CLI v0.1.4
Bazarr API is healthy.
Error: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

**Comment by madejackson** [comment]
Short update, i was able to fix it on my side. I used a base docker image to talk directly to bazarr, circumventing traefik (woahbase/alpine-ssh)

I just installed it the manual way inside this container and run the bb commands and it works.

**Comment by mateoradman** [comment]
I understand the problem now, and will push a fix soon. Thanks

**Comment by mateoradman** [comment]
v0.1.5 is released including the fix for base URL. You can set your base URL in the config.json file.

Example:

```json
{
  "host": "0.0.0.0",
  "protocol": "http",
  "apiKey": "<YOUR_API_KEY>",
  "port": "6767",
  "baseUrl": "bazarr" <- OPTIONAL field (may include trailing/leading slash) 
}
```

Thanks for your involvement in resolving this problem.
