### ISSUE TITLE
Investigate system dependencies required to run bazarr-bulk

### ISSUE THREAD

**Issue by madejackson** [mateoradman/bazarr-bulk#8]
- On debian, installation fails because it's missing libssl-dev (sudo apt install libssl-dev)

- On Alpine, installation fails because it's missing openssl-dev (apk add --update openssl-dev)
- On Alpine, installation fails again with some other error:
` = note: /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssl: No such file or directory
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lcrypto: No such file or directory
          collect2: error: ld returned 1 exit status`
- Manual install on Alpine throws an error: `bash: /usr/local/bin/bb: cannot execute: required file not found`

**Comment by mateoradman** [comment]
Thank you very much for reporting this issue. Apologies for the oversight. I will investigate all requirements on different systems and add them to the Installation docs.
